iShelter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shelter.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shelter/urls.py
from django.urls import path
from .views import home_view, shelter_view, pet_view

urlpatterns = [
    path('', home_view, name='home_view'),
    path('shelter/<int:shelter_id>', shelter_view, name='shelter_view'),
    path('pet/<int:pet_id>', pet_view, name='pet_view')
]

shelter/models.py
from datetime import date

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models
from django.core import validators


# Create your models here.

class Shelter(models.Model):
    name = models.TextField(max_length=32, verbose_name='Shelter Name')
    address = models.TextField(max_length=64, verbose_name='Shelter Address')
    capacity = models.IntegerField(validators=[validators.MinValueValidator(0)], verbose_name='Shelter Capacity')

    def __str__(self):
        return self.name


class Pet(models.Model):
    SEX_OPTIONS = [
        (True, 'Male'),
        (False, 'Female')
    ]

    name = models.TextField(max_length=32, verbose_name='Pet Name')
    birth_date = models.DateField(verbose_name='Pet Birth Date')
    sex = models.BooleanField(choices=SEX_OPTIONS)
    description = models.TextField(max_length=512, verbose_name='Pet Description')
    weight = models.FloatField(verbose_name='Pet Weight')
    shelter = models.ForeignKey('Shelter', on_delete=models.CASCADE)


    def __str__(self):
        return self.name

    @property
    def main_photo(self):
        try:
            return self.petphoto_set.get(main=True)
        except PetPhoto.DoesNotExist:
            return None

    @property
    def secondary_photos(self):
        return self.petphoto_set.filter(main=False)

    def cast(self):
        if hasattr(self, 'dogpet'):
            return self.dogpet
        elif hasattr(self, 'catpet'):
            return self.catpet
        elif hasattr(self, 'furypet'):
            return self.furypet
        else:
            return self
    @property
    def age(self):
        today = date.today()
        return today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))


class Breed(models.Model):
    name = models.TextField(max_length=32, verbose_name='Breed\'s Name')

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class DogBreed(Breed):
    pass


class CatBreed(Breed):
    pass


class DogPet(Pet):
    breed = models.ForeignKey('DogBreed', on_delete=models.CASCADE)


class CatPet(Pet):
    breed = models.ForeignKey('CatBreed', on_delete=models.CASCADE)


class FuryPet(Pet):
    pass


class PetPhoto(models.Model):
    photo = models.ImageField(verbose_name='Photo')
    pet = models.ForeignKey('Pet', on_delete=models.CASCADE)
    main = models.BooleanField(default=False)

    def clean(self):
        # Custom validation for 'main' field
        if self.main:
            # Check for other 'main' photos for the same pet, excluding this instance if it already exists
            other_main_photos = PetPhoto.objects.filter(pet=self.pet, main=True).exclude(id=self.id)
            if other_main_photos.exists():
                raise ValidationError('A pet can only have one main photo.')

    def save(self, *args, **kwargs):
        self.full_clean()  # Call the full_clean method to run model validation
        super(PetPhoto, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.pet.name} - {'main' if self.main else 'other'}"

shelter/views.py
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView

from shelter.models import CatPet, DogPet, Shelter, Pet, FuryPet


# Create your views here.
def home_view(request):
    return render(request, 'shelter/home.html', {'cats': CatPet.objects.all(),
                                                 'dogs': DogPet.objects.all(),
                                                 'furies': FuryPet.objects.all()})


def shelter_view(request, shelter_id):
    shelter = get_object_or_404(Shelter, pk=shelter_id)
    return render(request, 'shelter/shelter.html', {'shelter': shelter,
                                                    'cats': CatPet.objects.filter(shelter=shelter),
                                                    'dogs': DogPet.objects.filter(shelter=shelter),
                                                    'furies': FuryPet.objects.filter(shelter=shelter)})


def pet_view(request, pet_id):
    pet = get_object_or_404(Pet, pk=pet_id)
    # Get ContentType instances for CatPet and DogPet
    cat_content_type = ContentType.objects.get_for_model(CatPet)
    dog_content_type = ContentType.objects.get_for_model(DogPet)
    fury_content_type = ContentType.objects.get_for_model(FuryPet)

    return render(request, 'shelter/pet.html', {'pet': pet, 'cat_content_type_id': cat_content_type.id,
                                                'dog_content_type_id': dog_content_type.id,
                                                'fury_content_type': fury_content_type})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon" href="media/headpic.png" type="image/x-icon">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-center">
    <a class="navbar-brand" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">iShelter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home_view' %}">Home <span class="sr-only">(current)</span></a>

            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Shelters</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    About Us
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Who are we?</a>
                    <a class="dropdown-item" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Where are we?</a>
                    <a class="dropdown-item" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">FAQS</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Support us!</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>

<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/shelter/home.html
{% extends 'base.html' %}
{% block title %} Our animals {% endblock %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="../styles.css">

{% block content %}
      <div class="jumbotron text-center bg-light" style="background-image: url('media/cover.png'); background-size: cover; background-position: top;">
  <h1>iShelter</h1>
  <p>Save an animal, save a life.</p>
</div>
        <div class="custom-container mt-5 bg-light">
                <div class="text-center" style="font-family: 'Dubai Medium',ui-serif; font-size: 50px">
                    Cats
                </div>
            <div class="row">
                {% for cat in cats %}
                    <div class="col-12 col-md-6 col-xl-3 d-flex justify-content-center" style="cursor: pointer;" onclick="location.href='{% url 'pet_view' pet_id=cat.id %}'">
                        <div class="card m-4" style="width: 18rem;">
                            {% if cat.main_photo %}
                                <img src="{{ cat.main_photo.photo.url }}" class="card-img-top" alt="{{ cat.name }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ cat.name }} - {{ cat.breed.name }}</h5>
                                <a class="card-text" href="{% url 'shelter_view' shelter_id=cat.shelter.id%}">{{ cat.shelter.name }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container mt-5 bg-light">
            <div class="text-center" style="font-family: 'Dubai Medium',ui-serif; font-size: 50px">
                    Dogs
            </div>
            <div class="row">
                {% for dog in dogs %}
                    <div class="col-12 col-md-4 col-xl-3 d-flex justify-content-center" style="cursor: pointer;" onclick="location.href='{% url 'pet_view' pet_id=dog.id %}'">
                        <div class="card m-2" style="width: 18rem;">
                            {% if dog.main_photo %}
                                <img src="{{ dog.main_photo.photo.url }}" class="card-img-top" alt="{{ dog.name }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ dog.name }} - {{ dog.breed.name }}</h5>
                                <a class="card-text" href="{% url 'shelter_view' shelter_id=dog.shelter.id%}">{{ dog.shelter.name }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="container mt-5 bg-light">
            <div class="text-center" style="font-family: 'Dubai Medium',ui-serif; font-size: 50px">
                    Furies
            </div>
            <div class="row">
                {% for fury in furies %}
                    <div class="col-12 col-md-4 col-xl-3 d-flex justify-content-center" style="cursor: pointer;" onclick="location.href='{% url 'pet_view' pet_id=fury.id %}'">
                        <div class="card m-2" style="width: 18rem;">
                            {% if fury.main_photo %}
                                <img src="{{ fury.main_photo.photo.url }}" class="card-img-top" alt="{{ fury.name }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ fury.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock
{% endblock %}

templates/shelter/pet.html
{% extends 'base.html' %}
{% block title %}{{ pet.name }}{% endblock %}


{% block content %}
    <div class="jumbotron text-center bg-light" style="background-image: url('media/cover.png'); background-size: cover; background-position: top;">
  <h1>iShelter</h1>
  <p>Save an animal, save a life.</p>
    </div>
    <div class="container">
        <div class="container mt-5">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            {% if pet.main_photo %}
                                <div class="carousel-item active">
                                    <img class="d-block w-100" style="height: 50vh; object-fit: cover"
                                         src="{{ pet.main_photo.photo.url }}" alt="Pet photo">
                                </div>
                            {% endif %}
                            {% for photo in pet.secondary_photos %}
                                <div class="carousel-item">
                                    <img class="d-block w-100 {% if forloop.first and not pet.main_photo %}active{% endif %}"
                                         style="height: 50vh; object-fit: cover" src="{{ photo.photo.url }}"
                                         alt="Pet photo">
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <h1 style="font-family: Dubai,serif">{{ pet.name }}</h1>
                    <h5 style="font-family: Dubai,serif">{{ pet.cast.breed.name }}</h5>
                    <h5 style="font-family: Dubai,serif">Age: {{ pet.age }}</h5>
                    <h5 style="font-family: Dubai,serif">Sex: {{ pet.get_sex_display }}</h5>
                    <h5 style="font-family: Dubai,serif">{{ pet.shelter.name }}</h5>
                    <br>
                    <p>{{ pet.description }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/shelter/shelter.html
{% extends 'base.html' %}
{% block title %}{{ shelter.name }}{% endblock %}

{% block content %}
    <div class="jumbotron text-center bg-light">
        <h1>{{ shelter.name }}'s Pets</h1>
        <h4>Capacity: {{ shelter.pet_set.count }}/{{ shelter.capacity }}</h4>
        <h4>Address: {{ shelter.address }}</h4>
    </div>
        <div class="container mt-5">
            <h2>Cats</h2>
            <div class="row">
                {% for cat in cats %}
                    <div class="col-12 col-md-6 col-xl-4 d-flex justify-content-center" style="cursor: pointer;" onclick="location.href='{% url 'pet_view' pet_id=cat.id %}'">
                        <div class="card m-2" style="width: 18rem;">
                            {% if cat.main_photo %}
                                <img src="{{ cat.main_photo.photo.url }}" class="card-img-top" alt="{{ cat.name }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ cat.name }} - {{ cat.breed.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="container mt-5">
            <h2>Dogs</h2>
            <div class="row">
                {% for dog in dogs %}
                    <div class="col-12 col-md-4 d-flex justify-content-center" style="cursor: pointer;" onclick="location.href='{% url 'pet_view' pet_id=dog.id %}'">
                        <div class="card m-2" style="width: 18rem;">
                            {% if dog.main_photo %}
                                <img src="{{ dog.main_photo.photo.url }}" class="card-img-top" alt="{{ dog.name }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ dog.name }} - {{ dog.breed.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    <div class="container mt-5">
            <h2>Furies</h2>
            <div class="row">
                {% for fury in furies %}
                    <div class="col-12 col-md-4 d-flex justify-content-center" style="cursor: pointer;" onclick="location.href='{% url 'pet_view' pet_id=fury.id %}'">
                        <div class="card m-2" style="width: 18rem;">
                            {% if fury.main_photo %}
                                <img src="{{ fury.main_photo.photo.url }}" class="card-img-top" alt="{{ fury.name }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ fury.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}